name: CI/CD
on:
  push:
    paths:
      - '**.go'
      - go.mod
      - go.sum
      - .github/workflows/CICD.yml

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.*'
          cache: true
      - run: go test github.com/noah-friedman/speelcraft-mgr